name: dynomo
channels:
  - pytorch3d
  - pyg
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
dependencies:
  - cudatoolkit
  - pip
  - python=3.12
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pip:
      - click
      - gdown
      - h5py
      - imageio
      - imageio-ffmpeg
      - natsort
      - opencv-python
      - pillow
      - scikit-learn
      - setuptools
      - tqdm