name: dynomo
channels:
  - pytorch3d
  - pyg
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
dependencies:
  - cudatoolkit
  - faiss-gpu
  - pip
  - pillow
  - python=3.12
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - torchvision=0.20.1
  - pip:
      - absl-py
      - click
      - flow_vis
      - gdown
      - h5py
      - imageio
      - imageio-ffmpeg
      - kornia
      - matplotlib
      - mediapy
      - natsort
      - open3d
      - opencv-python
      - pandas
      - pytorch-msssim
      - roma
      - scikit-learn
      - setuptools
      - torchmetrics
      - tqdm
      - wandb